[project]
name = "django-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.4",
    "django-stubs>=5.1.1",
    "django-tailwind[reload]>=3.8.0",
    "environs[django]>=14.0.0",
]
